// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhkiLQ2H_PlfkP6zXc_TLpE8gnT8XOliw',
    appId: '1:619679226940:android:6bbbf1f1e00daa4b24f739',
    messagingSenderId: '619679226940',
    projectId: 'panun-kaergar-a162d',
    storageBucket: 'panun-kaergar-a162d.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxMJ1-ztZeF4LrstwJwTKsEX8MGhiWK7M',
    appId: '1:619679226940:ios:ec09859d1f44e38a24f739',
    messagingSenderId: '619679226940',
    projectId: 'panun-kaergar-a162d',
    storageBucket: 'panun-kaergar-a162d.appspot.com',
    androidClientId: '619679226940-542n1861pa45em8jm10adnvln9fd3g8k.apps.googleusercontent.com',
    iosClientId: '619679226940-dc4m5ps9lgths0s4cco3ico6moui9134.apps.googleusercontent.com',
    iosBundleId: 'com.panunkaergar.provider.app',
  );
}
